### PR TITLE
Support for vl53l1x

### PR DESCRIPTION
**Pull request by samuk**
## Description
Files from https://github.com/pololu/vl53l1x-arduino

## Solved issue(s)
vl53l1x sensors are supported

### CODE REVIEW

**Comment by platisd** [comment]
Thanks for submitting this pull request.
Can you please describe the benefit of adding this source code into the library? :thinking: 
What would for example be the benefit of incorporating them into `smartcar_shield` compared to fetching and using them as a separate library (which they already are)?

Furthermore, usefulness aside, for this to become part of the library, the following things would be missing:
1. Connection to one or more library interfaces, e.g. implement the `DistanceSensor` interface
2. Unit tests
3. Examples

**Comment by samuk** [comment]
I was hoping to implement the DistanceSensor interface.  Could you help with that?

**Comment by platisd** [comment]
> I was hoping to implement the DistanceSensor interface. Could you help with that?

Maybe I could, but that's the simplest part. First, I would need to understand what would the usefulness of such a feature. :)

**Comment by samuk** [comment]
The sensors would have the same utility as the existing Sharp or Ultrasonic sensors? https://github.com/platisd/smartcar_shield/tree/master/src/sensors/distance

**Comment by platisd** [comment]
> The sensors would have the same utility as the existing Sharp or Ultrasonic sensors? https://github.com/platisd/smartcar_shield/tree/master/src/sensors/distance

Sure, but why? What would be the benefit compared to users who want to use the particular sensor fetching the respective library and using it instead?
If this code gets introduced into the smartcar library, it needs to be maintained. The original authors of the `vl53l1x-arduino` library are way better than me/us in the specific sensor, which means that someone needs to **manually** port any changes of the original library into this one. Also I am not a big fan of mixing licenses since theirs is not MIT.

I can potentially add an example here to show how a **user** of the Smartcar library would make the particular sensor work "as if it were a part of the Smartcar library" (i.e. by specializing the `DistanceSensor` interface) if that's what you actually want.

**Comment by samuk** [comment]
Yeah an example would be great, thanks.

**Pull request closed without merging**
